name: Publish on GitHub and Modrinth

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Check Environment Variables
        run: env
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

          game-versions: 1.21.1
          game-version-filter: none

          version-type: release